default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: bloccit_development

test:
  <<: *default
  database: bloccit_test

production:
  <<: "https://evening-castle-14246.herokuapp.com"
  database: bloccit_test
